---
- name: restart checkmk-agent
  hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: restart the checkmk-agent daemon
      command: "{{ item }}"
      with_items:
        - "systemctl restart cmk-agent-ctl-daemon.service"
        - "systemctl restart check-mk-agent-async.service"
      
     