---
- name: restart checkmk-agent
  hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: restart the checkmk-agent daemon
      command: systemctl restart cmk-agent-ctl-daemon.service
      command: systemctl restart check-mk-agent-async.service