---
- hosts: minecraft03.int.local
  become: true
  tasks:
    - name: start ftb minecraft server
      command: sh /direwolf20-1.20-downgrade/start.sh
      args: 
        chdir: /direwolf20-1.20-downgrade