---
- hosts: mc01.int.local
  become: true
  tasks:
    - name: start ftb minecraft server
      command: sh /minecraft/FTB-Evolution/1.16.0//run.sh
      args: 
        chdir: /minecraft/FTB-Evolution/1.16.0